### ISSUE TITLE
Cross-compilation for Scala 3

### ISSUE THREAD

**Issue by JesusMtnez** [davenverse/fuuid#384]

**Comment by brbrown25** [comment]
I'd be willing to assist with this if you're interested.

**Comment by JesusMtnez** [comment]
> I'd be willing to assist with this if you're interested. 

Of course, feel free to participate and open the PR

**Comment by brbrown25** [comment]
I should have a PR in the next day or so, just working through the macro for scala 3

**Comment by JesusMtnez** [comment]
Done by #402
